# Generated by Django 4.1.6 on 2023-02-03 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Webpage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Contact', models.IntegerField()),
                ('Address', models.CharField(max_length=240)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FIRSTAPPLICATION.topic')),
            ],
        ),
    ]
